// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audio_processor.dart';
import 'api/audio_types.dart';
import 'api/bank_manager.dart';
import 'api/file_io.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -732650225;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_soundpax',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Float32List crateApiAudioProcessorAdjustVolume({
    required List<double> samples,
    required double gain,
  });

  SoundBank crateApiBankManagerCreateDefaultBank({
    required String name,
    required String dirPath,
  });

  void crateApiBankManagerDeleteBank({required String path});

  void crateApiFileIoDeleteSound({required String path});

  double crateApiAudioProcessorGetPeakLevel({required List<double> samples});

  SoundMeta crateApiFileIoGetSoundMeta({required String path});

  Float32List crateApiAudioProcessorGetWaveformData({
    required List<double> samples,
    required int numPoints,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  List<BankMeta> crateApiBankManagerListBanks({required String dirPath});

  List<SoundMeta> crateApiFileIoListSoundsInDir({required String dirPath});

  SoundBank crateApiBankManagerLoadBank({required String path});

  WavData crateApiFileIoLoadWav({required String path});

  Float32List crateApiAudioProcessorMixSamples({
    required List<Float32List> tracks,
    required List<double> volumes,
  });

  Float32List crateApiAudioProcessorNormalizeSamples({
    required List<double> samples,
  });

  void crateApiBankManagerSaveBank({
    required SoundBank bank,
    required String dirPath,
  });

  void crateApiFileIoSaveWav({
    required String path,
    required List<double> samples,
    required int sampleRate,
    required int channels,
  });

  Float32List crateApiAudioProcessorTrimSamples({
    required List<double> samples,
    required int startSample,
    required int endSample,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Float32List crateApiAudioProcessorAdjustVolume({
    required List<double> samples,
    required double gain,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_32_loose(samples, serializer);
          sse_encode_f_32(gain, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioProcessorAdjustVolumeConstMeta,
        argValues: [samples, gain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioProcessorAdjustVolumeConstMeta =>
      const TaskConstMeta(
        debugName: "adjust_volume",
        argNames: ["samples", "gain"],
      );

  @override
  SoundBank crateApiBankManagerCreateDefaultBank({
    required String name,
    required String dirPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(dirPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sound_bank,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBankManagerCreateDefaultBankConstMeta,
        argValues: [name, dirPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBankManagerCreateDefaultBankConstMeta =>
      const TaskConstMeta(
        debugName: "create_default_bank",
        argNames: ["name", "dirPath"],
      );

  @override
  void crateApiBankManagerDeleteBank({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBankManagerDeleteBankConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBankManagerDeleteBankConstMeta =>
      const TaskConstMeta(debugName: "delete_bank", argNames: ["path"]);

  @override
  void crateApiFileIoDeleteSound({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileIoDeleteSoundConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileIoDeleteSoundConstMeta =>
      const TaskConstMeta(debugName: "delete_sound", argNames: ["path"]);

  @override
  double crateApiAudioProcessorGetPeakLevel({required List<double> samples}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_32_loose(samples, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioProcessorGetPeakLevelConstMeta,
        argValues: [samples],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioProcessorGetPeakLevelConstMeta =>
      const TaskConstMeta(debugName: "get_peak_level", argNames: ["samples"]);

  @override
  SoundMeta crateApiFileIoGetSoundMeta({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sound_meta,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileIoGetSoundMetaConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileIoGetSoundMetaConstMeta =>
      const TaskConstMeta(debugName: "get_sound_meta", argNames: ["path"]);

  @override
  Float32List crateApiAudioProcessorGetWaveformData({
    required List<double> samples,
    required int numPoints,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_32_loose(samples, serializer);
          sse_encode_u_32(numPoints, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioProcessorGetWaveformDataConstMeta,
        argValues: [samples, numPoints],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioProcessorGetWaveformDataConstMeta =>
      const TaskConstMeta(
        debugName: "get_waveform_data",
        argNames: ["samples", "numPoints"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  List<BankMeta> crateApiBankManagerListBanks({required String dirPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dirPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bank_meta,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBankManagerListBanksConstMeta,
        argValues: [dirPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBankManagerListBanksConstMeta =>
      const TaskConstMeta(debugName: "list_banks", argNames: ["dirPath"]);

  @override
  List<SoundMeta> crateApiFileIoListSoundsInDir({required String dirPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dirPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_sound_meta,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileIoListSoundsInDirConstMeta,
        argValues: [dirPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileIoListSoundsInDirConstMeta =>
      const TaskConstMeta(
        debugName: "list_sounds_in_dir",
        argNames: ["dirPath"],
      );

  @override
  SoundBank crateApiBankManagerLoadBank({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sound_bank,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBankManagerLoadBankConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBankManagerLoadBankConstMeta =>
      const TaskConstMeta(debugName: "load_bank", argNames: ["path"]);

  @override
  WavData crateApiFileIoLoadWav({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wav_data,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileIoLoadWavConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileIoLoadWavConstMeta =>
      const TaskConstMeta(debugName: "load_wav", argNames: ["path"]);

  @override
  Float32List crateApiAudioProcessorMixSamples({
    required List<Float32List> tracks,
    required List<double> volumes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_list_prim_f_32_strict(tracks, serializer);
          sse_encode_list_prim_f_32_loose(volumes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioProcessorMixSamplesConstMeta,
        argValues: [tracks, volumes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioProcessorMixSamplesConstMeta =>
      const TaskConstMeta(
        debugName: "mix_samples",
        argNames: ["tracks", "volumes"],
      );

  @override
  Float32List crateApiAudioProcessorNormalizeSamples({
    required List<double> samples,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_32_loose(samples, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioProcessorNormalizeSamplesConstMeta,
        argValues: [samples],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioProcessorNormalizeSamplesConstMeta =>
      const TaskConstMeta(
        debugName: "normalize_samples",
        argNames: ["samples"],
      );

  @override
  void crateApiBankManagerSaveBank({
    required SoundBank bank,
    required String dirPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_sound_bank(bank, serializer);
          sse_encode_String(dirPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiBankManagerSaveBankConstMeta,
        argValues: [bank, dirPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBankManagerSaveBankConstMeta =>
      const TaskConstMeta(
        debugName: "save_bank",
        argNames: ["bank", "dirPath"],
      );

  @override
  void crateApiFileIoSaveWav({
    required String path,
    required List<double> samples,
    required int sampleRate,
    required int channels,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_list_prim_f_32_loose(samples, serializer);
          sse_encode_u_32(sampleRate, serializer);
          sse_encode_u_16(channels, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiFileIoSaveWavConstMeta,
        argValues: [path, samples, sampleRate, channels],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFileIoSaveWavConstMeta => const TaskConstMeta(
    debugName: "save_wav",
    argNames: ["path", "samples", "sampleRate", "channels"],
  );

  @override
  Float32List crateApiAudioProcessorTrimSamples({
    required List<double> samples,
    required int startSample,
    required int endSample,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_32_loose(samples, serializer);
          sse_encode_u_32(startSample, serializer);
          sse_encode_u_32(endSample, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioProcessorTrimSamplesConstMeta,
        argValues: [samples, startSample, endSample],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioProcessorTrimSamplesConstMeta =>
      const TaskConstMeta(
        debugName: "trim_samples",
        argNames: ["samples", "startSample", "endSample"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BankMeta dco_decode_bank_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BankMeta(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      padCount: dco_decode_u_8(arr[2]),
      createdAt: dco_decode_String(arr[3]),
      modifiedAt: dco_decode_String(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SoundBank dco_decode_box_autoadd_sound_bank(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_sound_bank(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<BankMeta> dco_decode_list_bank_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bank_meta).toList();
  }

  @protected
  List<Float32List> dco_decode_list_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_list_prim_f_32_strict)
        .toList();
  }

  @protected
  List<PadAssignment> dco_decode_list_pad_assignment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_pad_assignment).toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SoundMeta> dco_decode_list_sound_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sound_meta).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PadAssignment dco_decode_pad_assignment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PadAssignment(
      padIndex: dco_decode_u_8(arr[0]),
      soundPath: dco_decode_opt_String(arr[1]),
      volume: dco_decode_f_32(arr[2]),
      loopEnabled: dco_decode_bool(arr[3]),
    );
  }

  @protected
  SoundBank dco_decode_sound_bank(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SoundBank(
      meta: dco_decode_bank_meta(arr[0]),
      assignments: dco_decode_list_pad_assignment(arr[1]),
    );
  }

  @protected
  SoundMeta dco_decode_sound_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SoundMeta(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      durationMs: dco_decode_u_32(arr[2]),
      sampleRate: dco_decode_u_32(arr[3]),
      channels: dco_decode_u_16(arr[4]),
      fileSizeBytes: dco_decode_u_64(arr[5]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WavData dco_decode_wav_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return WavData(
      samples: dco_decode_list_prim_f_32_strict(arr[0]),
      sampleRate: dco_decode_u_32(arr[1]),
      channels: dco_decode_u_16(arr[2]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BankMeta sse_decode_bank_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_padCount = sse_decode_u_8(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_modifiedAt = sse_decode_String(deserializer);
    return BankMeta(
      name: var_name,
      path: var_path,
      padCount: var_padCount,
      createdAt: var_createdAt,
      modifiedAt: var_modifiedAt,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SoundBank sse_decode_box_autoadd_sound_bank(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_sound_bank(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  List<BankMeta> sse_decode_list_bank_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BankMeta>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bank_meta(deserializer));
    }
    return ans_;
  }

  @protected
  List<Float32List> sse_decode_list_list_prim_f_32_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Float32List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_f_32_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<PadAssignment> sse_decode_list_pad_assignment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PadAssignment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pad_assignment(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SoundMeta> sse_decode_list_sound_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SoundMeta>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sound_meta(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PadAssignment sse_decode_pad_assignment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_padIndex = sse_decode_u_8(deserializer);
    var var_soundPath = sse_decode_opt_String(deserializer);
    var var_volume = sse_decode_f_32(deserializer);
    var var_loopEnabled = sse_decode_bool(deserializer);
    return PadAssignment(
      padIndex: var_padIndex,
      soundPath: var_soundPath,
      volume: var_volume,
      loopEnabled: var_loopEnabled,
    );
  }

  @protected
  SoundBank sse_decode_sound_bank(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_meta = sse_decode_bank_meta(deserializer);
    var var_assignments = sse_decode_list_pad_assignment(deserializer);
    return SoundBank(meta: var_meta, assignments: var_assignments);
  }

  @protected
  SoundMeta sse_decode_sound_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_durationMs = sse_decode_u_32(deserializer);
    var var_sampleRate = sse_decode_u_32(deserializer);
    var var_channels = sse_decode_u_16(deserializer);
    var var_fileSizeBytes = sse_decode_u_64(deserializer);
    return SoundMeta(
      name: var_name,
      path: var_path,
      durationMs: var_durationMs,
      sampleRate: var_sampleRate,
      channels: var_channels,
      fileSizeBytes: var_fileSizeBytes,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WavData sse_decode_wav_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_samples = sse_decode_list_prim_f_32_strict(deserializer);
    var var_sampleRate = sse_decode_u_32(deserializer);
    var var_channels = sse_decode_u_16(deserializer);
    return WavData(
      samples: var_samples,
      sampleRate: var_sampleRate,
      channels: var_channels,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bank_meta(BankMeta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_u_8(self.padCount, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.modifiedAt, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_sound_bank(
    SoundBank self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sound_bank(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_list_bank_meta(
    List<BankMeta> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bank_meta(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_f_32_strict(
    List<Float32List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_f_32_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pad_assignment(
    List<PadAssignment> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pad_assignment(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_sound_meta(
    List<SoundMeta> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sound_meta(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_pad_assignment(PadAssignment self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.padIndex, serializer);
    sse_encode_opt_String(self.soundPath, serializer);
    sse_encode_f_32(self.volume, serializer);
    sse_encode_bool(self.loopEnabled, serializer);
  }

  @protected
  void sse_encode_sound_bank(SoundBank self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bank_meta(self.meta, serializer);
    sse_encode_list_pad_assignment(self.assignments, serializer);
  }

  @protected
  void sse_encode_sound_meta(SoundMeta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_u_32(self.durationMs, serializer);
    sse_encode_u_32(self.sampleRate, serializer);
    sse_encode_u_16(self.channels, serializer);
    sse_encode_u_64(self.fileSizeBytes, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_wav_data(WavData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_f_32_strict(self.samples, serializer);
    sse_encode_u_32(self.sampleRate, serializer);
    sse_encode_u_16(self.channels, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
