// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Float32List normalizeSamples({required List<double> samples}) => RustLib
    .instance
    .api
    .crateApiAudioProcessorNormalizeSamples(samples: samples);

Float32List adjustVolume({
  required List<double> samples,
  required double gain,
}) => RustLib.instance.api.crateApiAudioProcessorAdjustVolume(
  samples: samples,
  gain: gain,
);

Float32List trimSamples({
  required List<double> samples,
  required int startSample,
  required int endSample,
}) => RustLib.instance.api.crateApiAudioProcessorTrimSamples(
  samples: samples,
  startSample: startSample,
  endSample: endSample,
);

Float32List getWaveformData({
  required List<double> samples,
  required int numPoints,
}) => RustLib.instance.api.crateApiAudioProcessorGetWaveformData(
  samples: samples,
  numPoints: numPoints,
);

double getPeakLevel({required List<double> samples}) =>
    RustLib.instance.api.crateApiAudioProcessorGetPeakLevel(samples: samples);

Float32List mixSamples({
  required List<Float32List> tracks,
  required List<double> volumes,
}) => RustLib.instance.api.crateApiAudioProcessorMixSamples(
  tracks: tracks,
  volumes: volumes,
);
