// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class BankMeta {
  final String name;
  final String path;
  final int padCount;
  final String createdAt;
  final String modifiedAt;

  const BankMeta({
    required this.name,
    required this.path,
    required this.padCount,
    required this.createdAt,
    required this.modifiedAt,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      padCount.hashCode ^
      createdAt.hashCode ^
      modifiedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BankMeta &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          padCount == other.padCount &&
          createdAt == other.createdAt &&
          modifiedAt == other.modifiedAt;
}

class PadAssignment {
  final int padIndex;
  final String? soundPath;
  final double volume;
  final bool loopEnabled;

  const PadAssignment({
    required this.padIndex,
    this.soundPath,
    required this.volume,
    required this.loopEnabled,
  });

  @override
  int get hashCode =>
      padIndex.hashCode ^
      soundPath.hashCode ^
      volume.hashCode ^
      loopEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PadAssignment &&
          runtimeType == other.runtimeType &&
          padIndex == other.padIndex &&
          soundPath == other.soundPath &&
          volume == other.volume &&
          loopEnabled == other.loopEnabled;
}

class SoundBank {
  final BankMeta meta;
  final List<PadAssignment> assignments;

  const SoundBank({required this.meta, required this.assignments});

  @override
  int get hashCode => meta.hashCode ^ assignments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SoundBank &&
          runtimeType == other.runtimeType &&
          meta == other.meta &&
          assignments == other.assignments;
}

class SoundMeta {
  final String name;
  final String path;
  final int durationMs;
  final int sampleRate;
  final int channels;
  final BigInt fileSizeBytes;

  const SoundMeta({
    required this.name,
    required this.path,
    required this.durationMs,
    required this.sampleRate,
    required this.channels,
    required this.fileSizeBytes,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      durationMs.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      fileSizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SoundMeta &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          durationMs == other.durationMs &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          fileSizeBytes == other.fileSizeBytes;
}

class WavData {
  final Float32List samples;
  final int sampleRate;
  final int channels;

  const WavData({
    required this.samples,
    required this.sampleRate,
    required this.channels,
  });

  @override
  int get hashCode =>
      samples.hashCode ^ sampleRate.hashCode ^ channels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WavData &&
          runtimeType == other.runtimeType &&
          samples == other.samples &&
          sampleRate == other.sampleRate &&
          channels == other.channels;
}
