// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'audio_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void saveBank({required SoundBank bank, required String dirPath}) => RustLib
    .instance
    .api
    .crateApiBankManagerSaveBank(bank: bank, dirPath: dirPath);

SoundBank loadBank({required String path}) =>
    RustLib.instance.api.crateApiBankManagerLoadBank(path: path);

List<BankMeta> listBanks({required String dirPath}) =>
    RustLib.instance.api.crateApiBankManagerListBanks(dirPath: dirPath);

SoundBank createDefaultBank({required String name, required String dirPath}) =>
    RustLib.instance.api.crateApiBankManagerCreateDefaultBank(
      name: name,
      dirPath: dirPath,
    );

void deleteBank({required String path}) =>
    RustLib.instance.api.crateApiBankManagerDeleteBank(path: path);
