// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'audio_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void saveWav({
  required String path,
  required List<double> samples,
  required int sampleRate,
  required int channels,
}) => RustLib.instance.api.crateApiFileIoSaveWav(
  path: path,
  samples: samples,
  sampleRate: sampleRate,
  channels: channels,
);

WavData loadWav({required String path}) =>
    RustLib.instance.api.crateApiFileIoLoadWav(path: path);

SoundMeta getSoundMeta({required String path}) =>
    RustLib.instance.api.crateApiFileIoGetSoundMeta(path: path);

List<SoundMeta> listSoundsInDir({required String dirPath}) =>
    RustLib.instance.api.crateApiFileIoListSoundsInDir(dirPath: dirPath);

void deleteSound({required String path}) =>
    RustLib.instance.api.crateApiFileIoDeleteSound(path: path);
